

config:
  queries:
    reportMetadata: " select * from matric_metadata where record_id=?"
    dqRules: "select * from dqrules where record_id=?"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: root
    driver-class-name: "com.mysql.jdbc.Driver"

